INSERT INTO USERS(ID, USER_NAME, AGE) values(nextval('USERS_SEQ'),'Venkata','1999-05-28');
INSERT INTO USERS(ID, USER_NAME, AGE) values(nextval('USERS_SEQ'),'Rajesh','2000-04-28');
INSERT INTO USERS(ID, USER_NAME, AGE) values(nextval('USERS_SEQ'),'Pranav','2020-04-28');

INSERT INTO POSTS(ID, DESCRIPTION, USER_ID) values(nextval('POSTS_SEQ'), 'User 1 Post 1', SELECT ID FROM USERS WHERE USER_NAME = 'Venkata');
INSERT INTO POSTS(ID, DESCRIPTION, USER_ID) values(nextval('POSTS_SEQ'), 'User 1 Post 2', SELECT ID FROM USERS WHERE USER_NAME = 'Venkata');
INSERT INTO POSTS(ID, DESCRIPTION, USER_ID) values(nextval('POSTS_SEQ'), 'User 2 Post 1', SELECT ID FROM USERS WHERE USER_NAME = 'Rajesh');